### ISSUE TITLE
Spain validation incorrect

### ISSUE THREAD

**Issue by ambulanca** [loophp/tin#27]
## Steps required to reproduce the problem

1. $bool = TIN::fromSlug('esX1042189J')->isValid();

## Expected Result
TRUE
-

## Actual Result
FALSE
-

**Comment by drupol** [comment]
Hello,

Have you tried with `X1042189J` only ?

**Comment by drupol** [comment]
The issue has been identified... fix is coming.

**Comment by ambulanca** [comment]
No, I tried with some others too... another example X1143189C

**Comment by drupol** [comment]
The issue has been fixed, thanks for reporting it.

The fix is included in the new version 1.1.1 that has just been published a few seconds ago.

**Comment by drupol** [comment]
Dear @ambulanca ,

Can you provide some feedback with the new release? Is the fix working for you?

Thanks.

**Comment by ambulanca** [comment]
It's working, thanks
