### ISSUE TITLE
Feature request: Throw specific exceptions

### ISSUE THREAD

**Issue by tomsommer** [loophp/tin#3]
It would be a lot easier to deal with errors if logic-specific exceptions were thrown, such as 

`InvalidCountryTINException` `InvalidDateTinException` etc.

Right now there is no way to check the reasons behind `TINException`

**Comment by drupol** [comment]
Hi Tom!

Thanks for your suggestion, this is actually something that I have to do, but I don't have much time to dedicate to this project anymore.

Are you willing to contribute in a way ?

Thanks !

**Comment by drupol** [comment]
@tomsommer Did you received my email?

**Comment by drupol** [comment]
@tomsommer kind reminder! :) ^^

**Comment by drupol** [comment]
@tomsommer still alive there?

**Comment by drupol** [comment]
Ok closing this. Thank you very much.
