### ISSUE TITLE
Add this new function to TIN.php

### ISSUE THREAD

**Issue by ortegafernando** [loophp/tin#44]
Hello, as we can not catch the invalidCountry exception exclusively, I think this function will be good to detect is the TIN's country BEFORE using check function.

```
    public function hasAlgorithm(): bool
    {
        $parsedTin = $this->parse($this->slug, false);
        foreach ($this->algorithms as $algorithm) {
            if (true === $algorithm::supports($parsedTin['country'])) {
                return true;
            }
        }
        return false;
    }
```

I can make a PULL REQUEST if you want.

**Comment by ortegafernando** [comment]
Hi, what about last PR ?

**Comment by drupol** [comment]
Hi,

Sorry, I'm a bit overwhelmed with work lately...

How about adding just `Tin::isSupported():bool` ?

**Comment by iekadou** [comment]
Solved by https://github.com/loophp/tin/pull/46, correct? :)

**Comment by drupol** [comment]
yes, thank you !
